version: '3'

networks:
  openstudybuilder-network:
    driver: bridge

volumes:
  # Volume for storing the database on a local development environment
  openstudybuilder-database:
    name: openstudybuilder-database

services:
  # Database service for local development
  database:
    container_name: openstudybuilder-database
    image: hudzy/openstudybuilder:database
    build:
      args:
        NEO4J_server_memory_heap_initial__size: "3G"
        NEO4J_server_memory_heap_max__size: "3G"
        NEO4J_server_memory_pagecache_size: "2G"
      context: ./
      dockerfile: database.Dockerfile
    environment:
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_server_memory_heap_initial__size: "2G"
      NEO4J_server_memory_heap_max__size: "2G"
      NEO4J_server_memory_pagecache_size: "1G"
      NEO4J_server_default__listen__address: "0.0.0.0" #localhost
      # NEO4J_server_bolt_advertised__address: "localhost:5002" #:7687
      # NEO4J_server_http_advertised__address: "localhost:5001" #:7474
    networks:
      - openstudybuilder-network
    ports:
      - "7687:7687" # bolt
      - "7474:7474" # http
    volumes:
      - type: volume
        source: openstudybuilder-database
        target: /data
      #- ./neo4j-data:/data

  # Neodash service used with defined parameters
  neodash:
    container_name: openstudybuilder-neodash
    image: neo4jlabs/neodash:2.4.8
    depends_on:
      database:
        condition: service_healthy
    networks:
      - openstudybuilder-network
    ports:
      - "5007:5007"
    environment:
      NGINX_PORT: 5007
      ssoEnabled: false
      ssoDiscoveryUrl: https://localhost.com
      standalone: true
      standaloneProtocol: neo4j
      standaloneHost: localhost
      standalonePort: 7687 # 5002
      standaloneDatabase: mdrdb
      standaloneAllowLoad: true
      standaloneDashboardName: Activity Library Dashboard
      standaloneDashboardDatabase: mdrdb
      standaloneUsername: neo4j
      standalonePassword: changeme1234

  # Documentation portal image for production (see docs service for local development)
  documentation:
    container_name: openstudybuilder-documentation
    image: hudzy/openstudybuilder:documentation
    build:
      context: ./documentation-portal
      dockerfile: Dockerfile
    networks:
      - openstudybuilder-network
    ports:
      - "5006:5006"

  # API image & service, distinct build stages for production and development
  api:
    container_name: openstudybuilder-api
    image: hudzy/openstudybuilder:api
    build:
      context: ./clinical-mdr-api
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    networks:
      - openstudybuilder-network
    ports:
      - "5003:5003"
    environment:
      NEO4J_DSN: "bolt://neo4j:changeme1234@database:7687/mdrdb"
      ALLOW_ORIGIN_REGEX: ".*"
      OAUTH_ENABLED: "False"
      OAUTH_RBAC_ENABLED: "False"
      # OAUTH_METADATA_URL: "${OAUTH_METADATA_URL:-}"
      # OAUTH_API_APP_ID: "${OAUTH_API_APP_ID:-}"
      # OAUTH_API_APP_SECRET: "${OAUTH_API_APP_SECRET:-}"
      # OAUTH_SWAGGER_APP_ID: "${OAUTH_SWAGGER_APP_ID:-}"
      # MS_GRAPH_INTEGRATION_ENABLED: "${MS_GRAPH_INTEGRATION_ENABLED:-}"
      # MS_GRAPH_GROUPS_QUERY: "${MS_GRAPH_GROUPS_QUERY:-}"

  # Frontend image for production (see UI service for local development)
  frontend:
    container_name: openstudybuilder-frontend
    image: hudzy/openstudybuilder:frontend
    build:
      context: ./studybuilder
      dockerfile: Dockerfile
    depends_on:
      api:
        condition: service_healthy
      documentation:
        condition: service_healthy
      neodash:
        condition: service_healthy
    networks:
      - openstudybuilder-network
    ports:
      - "5005:5005"
    environment:
      API_BASE_URL: "${API_PATH:-}"
      DOC_BASE_URL: "${DOC_PATH:-}"
      NEODASH_BASE_URL: "${NEODASH_PATH:-}"
      OAUTH_ENABLED: "${OAUTH_ENABLED:-false}"
      # OAUTH_METADATA_URL: "${OAUTH_METADATA_URL:-}"
      # OAUTH_API_APP_ID: "${OAUTH_API_APP_ID:-}"
      # OAUTH_UI_APP_ID: "${OAUTH_UI_APP_ID:-}"
      APPINSIGHTS_DISABLE: "true"
