version: "3"

networks:
  openstudybuilder-network:
    driver: bridge

volumes:
  # Volume for storing the database on a local development environment
  openstudybuilder-database:
    name: openstudybuilder-database

services:
  # Database service for local development
  database:
    image: hudzy/openstudybuilder:database
    build:
      args:
        NEO4J_server_memory_heap_initial__size: "3G"
        NEO4J_server_memory_heap_max__size: "3G"
        NEO4J_server_memory_pagecache_size: "2G"
      context: ./
      dockerfile: database.Dockerfile

  # Documentation portal image for production (see docs service for local development)
  documentation:
    image: hudzy/openstudybuilder:documentation
    build:
      context: ./documentation-portal
      dockerfile: Dockerfile

  # API image & service, distinct build stages for production and development
  api:
    image: hudzy/openstudybuilder:api
    build:
      context: ./clinical-mdr-api
      dockerfile: Dockerfile

  # Frontend image for production (see UI service for local development)
  frontend:
    image: hudzy/openstudybuilder:frontend
    build:
      context: ./studybuilder
      dockerfile: Dockerfile
