name: OpenStudyBuilder-Solution-CI

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - ./docker-compose-build.yaml
  #     - ./database.Dockerfile
  #     - ./documentation-portal/Dockerfile
  #     - ./clinical-mdr-api/Dockerfile
  #     - ./studybuilder/Dockerfile

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: hudzy
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        working-directory: ./
        run: ./build-push-image.sh
